import { Song, Playlist, Artist, AudioAcousticProfile } from '@/types/music';



export const ACOUSTIC_PROFILES: AudioAcousticProfile[] = [
  {
    id: 'studio-master',
    name: 'Flat',
    icon: '🎵',
    description: 'Pristine 0dB flat studio reference standard',
    bassBoost: 0,
    trebleBoost: 0,
    midBoost: 0,
    reverbLevel: 0,
  },
  {
    id: 'bass-punch',
    name: 'Bass Boost',
    icon: '🔊',
    description: 'Heavy sub-bass punch (+8dB) and deep 808 low-end weight',
    bassBoost: 8.0,
    trebleBoost: 0.0,
    midBoost: 0.0,
    reverbLevel: 0.1,
  },
  {
    id: 'vocal-clarity',
    name: 'Vocal',
    icon: '🎤',
    description: 'Sub-bass cut with crisp forward vocal clarity & diction',
    bassBoost: -2.0,
    trebleBoost: 4.0,
    midBoost: 5.0,
    reverbLevel: 0.15,
  },
  {
    id: 'romantic',
    name: 'Romantic',
    icon: '💕',
    description: 'Enveloping warmth, chest resonance & airy intimacy',
    bassBoost: 3.0,
    trebleBoost: 4.0,
    midBoost: -1.0,
    reverbLevel: 0.3,
  },
  {
    id: 'pop',
    name: 'Pop',
    icon: '🎶',
    description: 'Punchy rhythmic beat with bright modern presence',
    bassBoost: 1.0,
    trebleBoost: 3.0,
    midBoost: 2.0,
    reverbLevel: 0.15,
  },
  {
    id: 'rock',
    name: 'Rock',
    icon: '🎸',
    description: 'Aggressive guitars, driving drums & sizzling highs',
    bassBoost: 5.0,
    trebleBoost: 5.0,
    midBoost: -1.0,
    reverbLevel: 0.2,
  },
  {
    id: 'cinema-spatial',
    name: 'Cinema Spatial',
    icon: '🌌',
    description: '3D holographic spatialization with theater sub-bass rumble',
    bassBoost: 6.0,
    trebleBoost: 9.0,
    midBoost: -2.0,
    reverbLevel: 1.0,
  },
  {
    id: 'lofi-warmth',
    name: 'Lo-Fi Warmth',
    icon: '☕',
    description: 'Vintage cassette rolloff (-12dB highs) with warm tube mid-bass',
    bassBoost: 7.0,
    trebleBoost: -12.0,
    midBoost: 2.0,
    reverbLevel: 0.1,
  },
];

// Authentic Verified Reference Tracks
export const INITIAL_SONGS: Song[] = [
  {
    id: 'real-1',
    name: 'Kesariya',
    artist: 'Arijit Singh, Pritam, Amitabh Bhattacharya',
    album: 'Brahmastra',
    year: '2022',
    duration: 268,
    cover: 'https://c.saavncdn.com/978/Brahmastra-Hindi-2022-20220815183856-500x500.jpg',
    streamUrl: 'https://aac.saavncdn.com/978/2b26090e5015b6d510c4c4be672e8ca9_320.mp4',
    quality: 'Lossless',
    source: 'jiosaavn',
    language: 'Hindi',
    hasLyrics: true,
    gradientColors: ['#f97316', '#7c2d12'],
    lyrics: [
      '[00:00.00] ♪ Kesariya Tera Ishq Hai Piya ♪',
      '[00:15.00] Mujhko itna bataye koi',
      '[00:22.00] Kaise tujhse dil na lagaye koi',
      '[00:30.00] Rabba ne tujhko banane me',
      '[00:38.00] Kar di hai husn ki khaali tijoriyan',
      '[00:46.00] Kajle ki siyahi se likhi',
      '[00:54.00] Hai tune jaane kitno ki love storiyan',
      '[01:05.00] Kesariya tera ishq hai piya',
      '[01:14.00] Rang jaaun jo main haath lagaun',
    ],
  },
  {
    id: 'real-2',
    name: 'Tauba Tauba',
    artist: 'Karan Aujla',
    album: 'Bad Newz',
    year: '2024',
    duration: 206,
    cover: 'https://c.saavncdn.com/152/Tauba-Tauba-From-Bad-Newz-Hindi-2024-20240702161048-500x500.jpg',
    streamUrl: 'https://aac.saavncdn.com/152/e53a209930f3674697368032c5750d43_320.mp4',
    quality: 'Lossless',
    source: 'jiosaavn',
    language: 'Punjabi',
    hasLyrics: true,
    gradientColors: ['#eab308', '#713f12'],
    lyrics: [
      '[00:00.00] Yeah Karan Aujla!',
      '[00:10.00] Hush hush husn tera tauba tauba',
      '[00:18.00] Husn tera tauba tauba',
    ],
  },
  {
    id: 'real-3',
    name: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    year: '2020',
    duration: 200,
    cover: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=800&auto=format&fit=crop',
    streamUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=electronic-future-beats-117997.mp3',
    quality: 'Opus',
    source: 'youtube',
    language: 'English',
    hasLyrics: true,
    gradientColors: ['#b81414', '#3d0505'],
    lyrics: [
      "[00:00.00] Yeah",
      "[00:12.00] I've been tryna call",
      "[00:16.00] I've been on my own for long enough",
      "[00:22.00] Maybe you can show me how to love, maybe",
      "[01:00.00] I said, ooh, I'm blinded by the lights",
      "[01:07.00] No, I can't sleep until I feel your touch",
    ],
  },
  {
    id: 'real-4',
    name: 'Lover',
    artist: 'Diljit Dosanjh',
    album: 'MoonChild Era',
    year: '2021',
    duration: 198,
    cover: 'https://c.saavncdn.com/393/MoonChild-Era-Punjabi-2021-20210822184920-500x500.jpg',
    streamUrl: 'https://aac.saavncdn.com/393/fafe6e147f872b2257d23d8c1c469f37_320.mp4',
    quality: 'Lossless',
    source: 'jiosaavn',
    language: 'Punjabi',
    hasLyrics: true,
    gradientColors: ['#ec4899', '#831843'],
  },
  {
    id: 'real-5',
    name: 'Channa Mereya',
    artist: 'Arijit Singh, Pritam',
    album: 'Ae Dil Hai Mushkil',
    year: '2016',
    duration: 289,
    cover: 'https://c.saavncdn.com/743/Ae-Dil-Hai-Mushkil-Deluxe-Hindi-2016-500x500.jpg',
    streamUrl: 'https://aac.saavncdn.com/743/33fead905c1066046e7f773347b2c019_320.mp4',
    quality: 'Lossless',
    source: 'jiosaavn',
    language: 'Hindi',
    hasLyrics: true,
    gradientColors: ['#3b82f6', '#1e3a8a'],
  },
];

export const INITIAL_PLAYLISTS: Playlist[] = [
  {
    id: 'pl-1',
    title: 'Daily Mix 1',
    description: 'Arijit Singh, Diljit Dosanjh, Karan Aujla, and deluxe chartbusters',
    cover: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=800&auto=format&fit=crop',
    songCount: 18,
    songs: INITIAL_SONGS.slice(0, 4),
    isPinned: true,
  },
  {
    id: 'pl-2',
    title: 'Punjabi Chartbusters',
    description: 'Tauba Tauba, Lover, Karan Aujla, Diljit Dosanjh',
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop',
    songCount: 24,
    songs: [INITIAL_SONGS[1], INITIAL_SONGS[3]],
    isPinned: true,
  },
  {
    id: 'pl-3',
    title: 'Arijit Singh Essentials',
    description: 'Kesariya, Channa Mereya, Tum Hi Ho, and timeless melodies',
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?q=80&w=800&auto=format&fit=crop',
    songCount: 32,
    songs: [INITIAL_SONGS[0], INITIAL_SONGS[4]],
    isPinned: true,
  },
  {
    id: 'pl-4',
    title: 'Heavy Rotation',
    description: 'Your most streamed tracks this month in pristine Hi-Fi',
    cover: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=800&auto=format&fit=crop',
    songCount: 15,
    songs: INITIAL_SONGS,
  },
];

export const INITIAL_ARTISTS: Artist[] = [
  {
    id: 'art-1',
    name: 'Arijit Singh',
    image: 'https://c.saavncdn.com/artists/Arijit_Singh_002_20230323062147_500x500.jpg',
    monthlyListeners: '42,439,210',
    verified: true,
    topSongs: [INITIAL_SONGS[0], INITIAL_SONGS[4]],
  },
  {
    id: 'art-2',
    name: 'Diljit Dosanjh',
    image: 'https://c.saavncdn.com/artists/Diljit_Dosanjh_004_20221006184545_500x500.jpg',
    monthlyListeners: '21,210,950',
    verified: true,
    topSongs: [INITIAL_SONGS[3]],
  },
  {
    id: 'art-3',
    name: 'Karan Aujla',
    image: 'https://c.saavncdn.com/artists/Karan_Aujla_003_20230818090712_500x500.jpg',
    monthlyListeners: '18,890,300',
    verified: true,
    topSongs: [INITIAL_SONGS[1]],
  },
];
